# Questions from https://opentdb.com/

question_data = [
        {"category": "Entertainment: Music",
         "type": "multiple", "difficulty": "medium",
         "question": "Who had a 1973 hit with the song &#039;Hocus Pocus&#039;?",
         "correct_answer": "Focus",
         "incorrect_answers": ["Pilot", "Rush", "AC\/DC"]
         },
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "Who is the artist of the recent new album the Uncanny Valley?", "correct_answer": "Perturbator",
         "incorrect_answers": ["Carpenter Brut", "GOST", "Dan Terminus "]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "Which American family band had a 1986 top 10 hit with the song &#039;Crush On You&#039;?",
         "correct_answer": "The Jets", "incorrect_answers": ["DeBarge", "The Jacksons", "The Cover Girls"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "What genre of EDM is the Dutch DJ, musician, and remixer Armin van Buuren most well-known for?",
         "correct_answer": "Trance", "incorrect_answers": ["House", "Drum and Bass", "Dubstep"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "Which song is not by TheFatRat?", "correct_answer": "Ascent",
         "incorrect_answers": ["Monody", "Windfall", "Infinite Power!"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "Which of these is NOT the name of an album released by American rapper Viper?",
         "correct_answer": "The Life of Pablo",
         "incorrect_answers": ["Kill Urself My Man", "You&#039;ll Cowards Don&#039;t Even Smoke Crack",
                               "Yo Wife Handcuffin&#039; Me"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "Which of these artists has NOT been a member of dancehall group Major Lazer?",
         "correct_answer": "Skrillex", "incorrect_answers": ["Diplo", "Jillionaire", "Walshy Fire"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "Which of these is NOT the name of an album released by Miami-based producer DJ Khaled?",
         "correct_answer": "Don&#039;t Ever Play Yourself",
         "incorrect_answers": ["Major Key", "Suffering From Success", "I Changed A Lot"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "Which one of these Pink Floyd albums were also a movie?", "correct_answer": "The Wall",
         "incorrect_answers": ["The Dark Side of the Moon", "Wish You Were Here", "Animals"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "What was the title of Sakamoto Kyu&#039;s song &quot;Ue o Muite Arukou&quot; (I Look Up As I Walk) changed to in the United States?",
         "correct_answer": "Sukiyaki", "incorrect_answers": ["Takoyaki", "Sushi", "Oden"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "Which country does the electronic music duo &quot;The Knife&quot; originate from?",
         "correct_answer": "Sweden", "incorrect_answers": ["Finland", "Denmark", "Norway"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "&quot;Lift Your Spirit&quot; is an album by which artist?", "correct_answer": "Aloe Blacc",
         "incorrect_answers": ["Lena Meyer-Landrut", "Stevie Wonder", "Taylor Swift"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "Which of these bands is the oldest?", "correct_answer": "Pink Floyd",
         "incorrect_answers": ["AC\/DC", "Metallica", "Red Hot Chili Peppers"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "How many copies have Metallica album &quot;Metallica&quot; (A.K.A The Black Album) sold worldwide (in Millions of Copies)?",
         "correct_answer": "20.5", "incorrect_answers": ["19.5", "22.5", "25.5"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "Which member of &quot;The Beatles&quot; narrated episodes of &quot;Thomas the Tank Engine&quot;?",
         "correct_answer": "Ringo Starr", "incorrect_answers": ["George Harrison", "John Lennon", "Paul McCartney"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "Which artist or group did John Lennon consider &quot;son(s) of the Beatles&quot;?",
         "correct_answer": "Jeff Lynne&#039;s Electric Light Orchestra",
         "incorrect_answers": ["The Rolling Stones", "Pink Floyd", "The Who"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
         "question": "Musical artist, Future, collaborated with Kendrick Lamar for the song: &quot;Mask Off&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "Which alternative rock band released the critically-acclaimed album &quot;OK Computer&quot;?",
         "correct_answer": "Radiohead", "incorrect_answers": ["R.E.M.", "Nirvana", "Coldplay"]},
        {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
         "question": "What country did Shirley Bassey originate from?", "correct_answer": "Wales",
         "incorrect_answers": ["America", "England", "Canada"]},
        {
            "category": "Entertainment: Music",
            "type": "multiple",
            "difficulty": "medium",
         "question": "&quot;The Genius&quot; is the original and secondary name of which Wu-Tang Clan member?",
         "correct_answer": "GZA",
         "incorrect_answers": ["Ghostface Killah", "Ol&#039; Dirty Bastard", "Raekwon the Chef"]}
]
